# Site settings
title: Dveamer
motto: 이상을 꿈꾸는 몽상가.. 프로그래밍을 좋아함..
email: dveamer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dveamer.github.io" # the base hostname & protocol for your site
twitter_username: dveamer
github_username:  dveamer
disqus_comment_username: Dveamer
disqus_domain: "https://dveamer.github.io" # fixed
excerpt_separator: <!--more-->
encoding: utf-8


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "fenced_code_blocks", "strikethrough", "hard_wrap"]

# highlighter: pygments
permalink: none
  
#markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    line_numbers: false

#  highlighter:  rouge
#  syntax_highlighter:  pygments

#markdown: redcarpet
#redcarpet:
#  extensions: ["footnotes"]
#paginate: 25
#paginate_path: "page:num/"
#permalink: "/:year/:month/:title.html"
